EMM_moduleTargets = nil;
EMM_TARGETS_OPTIONS = nil;
EMM_Current_Module = "none";
EMM_equipUI = nil;
EMM_Current_Module_path = nil;
EMM_Arsenal_filter = nil;
EMM_nested_currnetParentPath = nil;
EMM_var_disp_MODULE_MANAGER = nil;
// EMM_expandInvChkbox = nil;